name: Go Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.16'

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Build the Go project
      run: |
        go build -o qrcode_generator_reader main.go

    - name: Verify build
      run: |
        if [ ! -f "qrcode_generator_reader" ]; then
          echo "Build failed!"
          exit 1
        fi
        echo "Build successful!"

